export const SET_INPUT = "SET_INPUT";
export const FETCH_INIT = "FETCH_INIT";
export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_SERIES = "FETCH_SERIES";
export const FETCH_FAILED = "FETCH_FAILED";
export const FETCH_SINGLE_MOVIE_DETAILS = " FETCH_SINGLE_MOVIE_DETAILS";
export const FETCH_SINGLE_SERIES_DETAILS = "FETCH_SINGLE_SERIES_DETAILS";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
